# Generated by Django 3.2.15 on 2022-12-07 02:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('paid', 'Paid')], default='paid', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('payment_type', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('gopay', 'Gopay'), ('echannel', 'Echanel')], max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('expired', 'Expired'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('paid', 'Paid')], default='paid', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('outlet', models.IntegerField(null=True)),
                ('current_plan', models.IntegerField(null=True)),
                ('choosen_plan', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(null=True)),
                ('trial_unit', models.CharField(choices=[('D', 'Day'), ('W', 'Week'), ('M', 'Month'), ('Y', 'Year')], max_length=255, null=True)),
                ('trial_period', models.SmallIntegerField(null=True)),
                ('recurrence_unit', models.CharField(choices=[('D', 'Day'), ('W', 'Week'), ('M', 'Month'), ('Y', 'Year')], max_length=255, null=True)),
                ('recurrence_period', models.SmallIntegerField(null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=255, null=True, unique=True)),
                ('expires', models.DateTimeField(null=True)),
                ('billing_date', models.DateTimeField(null=True)),
                ('cancelled', models.BooleanField(null=True)),
                ('voucher', models.IntegerField(null=True)),
                ('active', models.BooleanField(null=True)),
                ('is_approved', models.BooleanField(default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.JSONField(max_length=255, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('deleted_by', models.JSONField(max_length=255, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('modified_by', models.JSONField(null=True)),
                ('billing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.billing')),
                ('outlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.outlet')),
                ('subscriptionplan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan')),
            ],
        ),
        migrations.AddField(
            model_name='billing',
            name='orderpayment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.orderpayment'),
        ),
        migrations.AddField(
            model_name='billing',
            name='subscriptiondetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptiondetail'),
        ),
    ]
