# Generated by Django 3.2.15 on 2022-12-16 03:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Client Name')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Phone Number')),
                ('business_code', models.CharField(max_length=255, null=True, verbose_name='Business Code')),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Brand Name')),
                ('brand_logo', models.CharField(max_length=255, null=True, verbose_name='Brand logo')),
                ('social_facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('social_twitter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter')),
                ('social_instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='Website')),
                ('registered_via', models.CharField(default='Kawn Subscriptions Manager', max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Province')),
            ],
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Outlet Name')),
                ('display_name', models.CharField(max_length=255, null=True, verbose_name='Display Name')),
                ('subscription_plan_read', models.CharField(max_length=255, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Phone Number')),
                ('province_read', models.CharField(max_length=255, null=True)),
                ('city_read', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Address')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', 'Invalid postal code')], verbose_name='Postal Code')),
                ('outlet_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Outlet Code')),
                ('outlet_image', models.URLField(null=True)),
                ('transaction_code_prefix', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction Code Prefix')),
                ('archieved', models.BooleanField(default=True)),
                ('deleted', models.CharField(max_length=255, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gratuity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('enable_dashboard', models.BooleanField(default=True)),
                ('branch_id', models.CharField(max_length=255, null=True)),
                ('device_users', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('province', models.IntegerField(null=True, verbose_name='Province')),
                ('city', models.IntegerField(null=True, verbose_name='City')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='City')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.province')),
            ],
        ),
    ]
